import React, { createContext, useContext, useState, useCallback, useMemo } from 'react';

const translations = {
  en: {
    // General
    admin: 'Admin',
    adminDashboard: 'Admin Dashboard',
    adminSubtitle: 'Manage government projects on-chain via Solana',
    connected: 'Connected',
    walletNotConnected: 'Wallet not connected',
    connectWallet: 'Connect Wallet',
    adminBadge: 'ADMIN',
    submit: 'Submit On-Chain',
    submitting: 'Sending to Solana...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    language: 'Language',

    // Access
    accessRequired: 'Admin Access Required',
    accessDesc: 'Connect your admin wallet (Phantom) to manage government projects on the Solana blockchain.',
    unauthorizedTitle: 'Unauthorized Wallet',
    unauthorizedDesc: 'This wallet is not authorized. Admin actions require the designated admin wallet.',
    connectedWallet: 'Connected wallet',

    // Tabs
    tabCreate: '📋 Create Project',
    tabAllocate: '💵 Allocate Budget',
    tabRelease: '📤 Release Funds',
    tabMilestone: '🎯 Milestones',
    tabDocument: '📄 Documents',
    tabClose: '🔒 Close Project',

    // Create Project
    createTitle: 'Create New Project (On-Chain)',
    projectId: 'Project ID',
    projectIdPlaceholder: 'e.g. kathmandu-bridge-007',
    projectName: 'Project Name',
    projectNamePlaceholder: 'Enter project name',
    province: 'Province',
    selectProvince: 'Select Province',
    district: 'District',
    selectDistrict: 'Select District',
    sector: 'Sector',
    selectSector: 'Select Sector',
    contractor: 'Contractor',
    contractorPlaceholder: 'Contractor name',
    totalBudget: 'Total Budget (NPR)',
    totalBudgetPlaceholder: 'Enter total budget',
    milestoneCount: 'Milestones',
    estimatedCompletion: 'Estimated Completion',
    description: 'Description (off-chain)',
    descriptionPlaceholder: 'Project description stored in MongoDB',
    budgetNote: 'Budget, name, and milestones stored on Solana. Province/district/description cached in MongoDB.',

    // Budget Summary
    budgetSummary: 'Budget Summary',
    allocatedBudget: 'Allocated Budget',
    releasedAmount: 'Released Amount',
    milestonesCompleted: 'Milestones Completed',
    utilizationRate: 'Utilization Rate',

    // Allocate
    allocateTitle: 'Allocate Budget (On-Chain)',
    selectProject: 'Select Project',
    amount: 'Amount (NPR)',
    amountPlaceholder: 'Enter amount',
    noteOffchain: 'Description (off-chain note)',

    // Release
    releaseTitle: 'Release Funds (On-Chain)',

    // Milestone
    milestoneTitle: 'Update Milestone (On-Chain)',
    milestoneIndex: 'Milestone Index (0-based)',
    milestoneDesc: 'Description',
    milestoneDescPlaceholder: 'Milestone description',
    milestoneStatus: 'Status',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    delayed: 'Delayed',

    // Document
    documentTitle: 'Record Document (On-Chain)',
    ipfsHash: 'IPFS Hash',
    ipfsHashPlaceholder: 'e.g. QmXo...',
    documentName: 'Document Name',
    documentNamePlaceholder: 'Enter document name',

    // Close
    closeTitle: 'Close Project (On-Chain)',
    closeWarning: '⚠️ Warning: Closing a project is permanent and recorded on-chain. No further mutations allowed.',
    selectActiveProject: 'Select Active Project',

    // Messages
    programNotLoaded: 'Program not loaded. Connect wallet first.',
    connectFirst: 'Connect wallet first.',
    projectCreated: 'Project created on-chain!',
    budgetAllocated: 'Budget allocated on-chain!',
    fundsReleased: 'Funds released on-chain!',
    milestoneUpdated: 'Milestone updated on-chain!',
    documentRecorded: 'Document recorded on-chain!',
    projectClosed: 'Project closed on-chain!',
    txLabel: 'TX',
    fillAllFields: 'Please fill all required fields.',
    invalidProgramId: 'Invalid Program ID. Check your .env configuration.',

    // Navbar
    home: 'Home',
    dashboard: 'Dashboard',
    projects: 'Projects',

    // Dashboard
    dashboardTitle: 'Project Overview',
    dashboardSubtitle: 'Real-time analytics and health of all government projects',
    totalBudgetLabel: 'Total Budget',
    allocated: 'Allocated',
    released: 'Released',
    projectsLabel: 'Projects',
    active: 'Active',
    utilization: 'Utilization',
    provinceSpending: 'Province-wise Spending',
    sectorDistribution: 'Sector Distribution',
    overallBudgetUtilization: 'Overall Budget Utilization',
    allocatedTotalBudget: 'Allocated / Total Budget',
    releasedAllocated: 'Released / Allocated',
    allocatedSuffix: 'allocated',
    totalSuffix: 'total',
    releasedSuffix: 'released',
    unallocatedFunds: 'Unallocated Funds',
    exploreAllProjects: 'Explore All Projects →',
    totalProjectsLabel: 'Total Projects',
    activeProjectsOverview: 'Active Projects',
    delayedProjectsLabel: 'Delayed Projects',
    completedProjectsLabel: 'Completed Projects',
    projectsByProvince: 'Projects by Province',
    projectStatusBreakdown: 'Project Status Breakdown',
    projectsBySector: 'Projects by Sector',
    milestoneProgressByProject: 'Milestone Progress by Project',
    recentFundReleases: 'Recent Fund Releases',
    recentlyUpdated: 'Recently Updated',
    totalLabel: 'Total',
    completedLabel: 'Done',
    progressLabel: 'Progress',
    viewProjectLink: 'View →',
    noRecentReleases: 'No recent fund releases',

    // Projects page
    closed: 'Closed',
    contractorLabel: 'Contractor',
    fundUtilization: 'Fund Utilization',
    milestonesLabel: 'Milestones',
    estCompletion: 'Est. Completion',
    govProjects: 'Government Projects',
    browseProjects: 'Browse and verify all funded projects across Nepal',
    allProvinces: 'All Provinces',
    allSectors: 'All Sectors',
    allStatus: 'All Status',
    activeStatus: 'Active',
    completedStatus: 'Completed',
    suspendedStatus: 'Suspended',
    showing: 'Showing',
    of: 'of',
    noProjectsMatch: 'No projects match your filters',

    // ProjectDetail
    projectNotFound: 'Project not found',
    demonstrationProject: 'Demonstration Project',
    demoProjectDesc: 'This project uses sample data for demonstration purposes. Transaction records shown here are simulated. Live on-chain transactions will appear once the project is registered on Solana devnet via admin operations.',
    completion: 'Completion',
    milestonePipeline: 'Milestone Pipeline',
    noMilestones: 'No milestones recorded yet',
    fundReleaseTimeline: 'Fund Release Timeline',
    fundReleaseHistory: 'Fund Release History',
    dateLabel: 'Date',
    amountLabel: 'Amount',
    descriptionLabel: 'Description',
    publicReviews: 'Public Reviews',
    ratingLabel: 'Rating:',
    feedbackPlaceholder: 'Share your feedback on this project...',
    submittingFeedback: 'Submitting...',
    submitReview: 'Submit Review',
    noReviews: 'No reviews yet. Be the first!',
    documentsIPFS: 'Documents (IPFS)',
    noDocuments: 'No documents uploaded yet',
    budgetAllocationsTitle: 'Budget Allocations',
    onChainData: 'On-Chain Data',
    projectPDA: 'Project PDA (Devnet)',
    recentTransactions: 'Recent Transactions',
    transactionHistory: 'Transaction History',
    sampleData: 'Sample Data',
    sampleTxNote: 'This project uses sample transaction data for demonstration. Live on-chain transactions will appear here once recorded via admin operations on Solana devnet.',
    noOnChainTx: 'No on-chain transaction records yet.',
    solanaExplorer: 'Solana Explorer',
    devnetCluster: 'Devnet Cluster',
    estimatedCompletionLabel: 'Estimated Completion',

    // Landing
    builtOnSolana: 'Built on Solana Blockchain',
    transparentTitle: 'Transparent',
    governmentFunds: 'Government Funds',
    forNepal: 'For Nepal',
    heroSubtitle: 'Every rupee tracked. Every project verifiable. Corruption is',
    technicallyRestricted: ' technically restricted ',
    heroSubtitleEnd: 'by blockchain rules — not empty promises.',
    viewBudget: 'View Budget →',
    exploreProjectsBtn: 'Explore Projects',
    immutableRecords: 'Immutable Records',
    publicVerification: 'Public Verification',
    noTampering: 'No Tampering',
    transparencyGlance: 'Transparency at a Glance',
    realtimeBlockchainData: 'Real-time data from the Solana blockchain',
    fundsReleasedLabel: 'Funds Released',
    activeProjectsLabel: 'Active Projects',
    utilizationRateLabel: 'Utilization Rate',
    howItWorks: 'How It Works',
    blockchainSteps: 'Blockchain-enforced transparency in 4 steps',
    stepProjectCreated: 'Project Created',
    stepProjectCreatedDesc: 'Government creates a public project on the blockchain with full budget details.',
    stepBudgetAllocated: 'Budget Allocated',
    stepBudgetAllocatedDesc: 'Funds allocated from treasury. Cannot exceed declared total budget — enforced by smart contract.',
    stepFundsReleased: 'Funds Released',
    stepFundsReleasedDesc: 'Every release recorded on-chain. Cannot exceed allocated amount. Tamper-proof history.',
    stepPublicVerification: 'Public Verification',
    stepPublicVerificationDesc: 'Any citizen verifies transactions on Solana Explorer. Complete transparency, zero trust needed.',
    whyBlockchain: 'Why Blockchain?',
    corruptionTitle: 'Corruption Cannot Survive On-Chain',
    corruptionDesc: 'Traditional government budget tracking relies on centralized databases that can be manipulated. Our system stores every financial transaction on the Solana blockchain — immutable, transparent, and verifiable by any citizen.',
    immutableLedger: 'Immutable Ledger',
    immutableLedgerDesc: 'Once recorded, transactions cannot be altered or deleted',
    smartContractRules: 'Smart Contract Rules',
    smartContractRulesDesc: 'Budget limits enforced by code, not administrators',
    realtimeAuditing: 'Real-time Auditing',
    realtimeAuditingDesc: 'Anyone can verify via Solana Explorer — no FOIA needed',
    readyToExplore: 'Ready to explore',
    transparentGovernance: 'transparent governance?',
    connectWalletCTA: 'Connect your Solana wallet and start verifying government spending in real-time. Every transaction is on-chain and publicly auditable.',

    // Welcome
    welcomeTagline1: 'Transparent Governance,',
    welcomeTagline2: 'On-Chain.',
    welcomeTagline3: 'For All.',
    welcomeSubtitle: 'A decentralized DApp tracking every rupee of government spending — immutable, verifiable, and open to every Nepali citizen.',
    letsExplore: "Let's Explore",
    solanaBlockchainBadge: 'Solana Blockchain',
    immutableRecordsBadge: 'Immutable Records',
    builtForNepal: 'Built for Nepal',
    decentralizedStrip: 'DECENTRALIZED · TRANSPARENT · TRUSTLESS',

    // Footer
    footerDesc: 'A decentralized government fund transparency system built on Solana blockchain. Making public spending transparent, immutable, and verifiable for every citizen of Nepal.',
    quickLinks: 'Quick Links',
    adminPanel: 'Admin Panel',
    blockchainLabel: 'Blockchain',
    devnetConnected: 'Devnet Connected',
    copyright: '© 2026 GovFund Nepal. Built on Solana Blockchain. All transactions are publicly verifiable.',
    forTransparentNepal: 'For a transparent Nepal',

    // ErrorBoundary
    somethingWrong: 'Something went wrong',
    unexpectedError: 'An unexpected error occurred. This might be a temporary issue.',
    showErrorDetails: 'Show error details',
    tryAgain: 'Try Again',
    reloadPage: 'Reload Page',
    errorHelp: 'If this keeps happening, check your wallet connection and ensure the Solana program is deployed to Devnet.',

    // IPFS
    connectingIPFS: 'Connecting to IPFS…',
    connectingGateway: 'Connecting to IPFS gateway…',
    checkingGateways: 'Checking multiple gateways',
    gatewayUnavailable: 'Gateway unavailable',
    tryDirectly: 'Try opening directly →',
    ipfsDocumentLabel: 'IPFS Document',

    // National Budget
    budgetTitle: 'National Budget Transparency',
    budgetSubtitle: 'Complete fiscal breakdown with on-chain verification',
    budgetNoData: 'No budget data available',
    budgetTotalAllocated: 'Total Budget Allocated',
    budgetTotalSpent: 'Total Spent So Far',
    budgetOverallUtil: 'Overall Utilization',
    budgetSplitTitle: 'Budget Split',
    budgetRecurrent: 'Recurrent Expenditure',
    budgetCapital: 'Capital Expenditure',
    budgetFinancialMgmt: 'Financial Management',
    budgetProvinceGrants: 'Province-wise Federal Grants',
    budgetFederalGrant: 'Federal Grant (B NPR)',
    budgetMinistryBreakdown: 'Ministry-wise Budget Breakdown',
    budgetAmount: 'Budget (B NPR)',
    budgetUtilization: 'Budget Utilization',
    budgetAllocatedLabel: 'Allocated',
    budgetSpentLabel: 'Spent',
    budgetCriticallyLow: 'Critically Low',
    budgetCat_Total: 'Total',
    budgetCat_Recurrent: 'Recurrent',
    budgetCat_Capital: 'Capital',
    budgetCat_FinancialManagement: 'Financial Management',
    budgetIpfsTitle: 'Tamper-proof IPFS Verification',
    budgetIpfsPending: 'Budget data not yet uploaded to IPFS',
    budgetVerifyIpfs: 'Verify on IPFS',
    budget: 'Budget',
  },

  ne: {
    // General
    admin: 'प्रशासक',
    adminDashboard: 'प्रशासक ड्यासबोर्ड',
    adminSubtitle: 'सोलाना ब्लकचेनमा सरकारी परियोजनाहरू व्यवस्थापन गर्नुहोस्',
    connected: 'जडित',
    walletNotConnected: 'वालेट जडित छैन',
    connectWallet: 'वालेट जडान गर्नुहोस्',
    adminBadge: 'प्रशासक',
    submit: 'अन-चेनमा पेश गर्नुहोस्',
    submitting: 'सोलानामा पठाउँदै...',
    cancel: 'रद्द गर्नुहोस्',
    confirm: 'पुष्टि गर्नुहोस्',
    success: 'सफल',
    error: 'त्रुटि',
    loading: 'लोड हुँदैछ...',
    language: 'भाषा',

    // Access
    accessRequired: 'प्रशासक पहुँच आवश्यक',
    accessDesc: 'सोलाना ब्लकचेनमा सरकारी परियोजनाहरू व्यवस्थापन गर्न आफ्नो प्रशासक वालेट (Phantom) जडान गर्नुहोस्।',
    unauthorizedTitle: 'अनधिकृत वालेट',
    unauthorizedDesc: 'यो वालेट अधिकृत छैन। प्रशासक कार्यहरूका लागि निर्दिष्ट प्रशासक वालेट आवश्यक छ।',
    connectedWallet: 'जडित वालेट',

    // Tabs
    tabCreate: '📋 परियोजना सिर्जना',
    tabAllocate: '💵 बजेट विनियोजन',
    tabRelease: '📤 कोष विमोचन',
    tabMilestone: '🎯 माइलस्टोन',
    tabDocument: '📄 कागजात',
    tabClose: '🔒 परियोजना बन्द',

    // Create Project
    createTitle: 'नयाँ परियोजना सिर्जना (अन-चेन)',
    projectId: 'परियोजना आईडी',
    projectIdPlaceholder: 'जस्तै kathmandu-bridge-007',
    projectName: 'परियोजना नाम',
    projectNamePlaceholder: 'परियोजना नाम प्रविष्ट गर्नुहोस्',
    province: 'प्रदेश',
    selectProvince: 'प्रदेश छान्नुहोस्',
    district: 'जिल्ला',
    selectDistrict: 'जिल्ला छान्नुहोस्',
    sector: 'क्षेत्र',
    selectSector: 'क्षेत्र छान्नुहोस्',
    contractor: 'ठेकेदार',
    contractorPlaceholder: 'ठेकेदार नाम',
    totalBudget: 'कुल बजेट (रु.)',
    totalBudgetPlaceholder: 'कुल बजेट प्रविष्ट गर्नुहोस्',
    milestoneCount: 'माइलस्टोनहरू',
    estimatedCompletion: 'अनुमानित समापन',
    description: 'विवरण (अफ-चेन)',
    descriptionPlaceholder: 'MongoDB मा भण्डारण हुने विवरण',
    budgetNote: 'बजेट, नाम, र माइलस्टोनहरू सोलानामा भण्डारण हुन्छ। प्रदेश/जिल्ला/विवरण MongoDB मा क्यास हुन्छ।',

    // Budget Summary
    budgetSummary: 'बजेट सारांश',
    allocatedBudget: 'विनियोजित बजेट',
    releasedAmount: 'विमोचित रकम',
    milestonesCompleted: 'माइलस्टोन पूरा',
    utilizationRate: 'उपयोग दर',

    // Allocate
    allocateTitle: 'बजेट विनियोजन (अन-चेन)',
    selectProject: 'परियोजना छान्नुहोस्',
    amount: 'रकम (रु.)',
    amountPlaceholder: 'रकम प्रविष्ट गर्नुहोस्',
    noteOffchain: 'विवरण (अफ-चेन नोट)',

    // Release
    releaseTitle: 'कोष विमोचन (अन-चेन)',

    // Milestone
    milestoneTitle: 'माइलस्टोन अपडेट (अन-चेन)',
    milestoneIndex: 'माइलस्टोन सूचकांक (०-आधारित)',
    milestoneDesc: 'विवरण',
    milestoneDescPlaceholder: 'माइलस्टोन विवरण',
    milestoneStatus: 'स्थिति',
    pending: 'पेन्डिङ',
    inProgress: 'प्रगतिमा',
    completed: 'सम्पन्न',
    delayed: 'ढिला',

    // Document
    documentTitle: 'कागजात रेकर्ड (अन-चेन)',
    ipfsHash: 'IPFS ह्यास',
    ipfsHashPlaceholder: 'जस्तै QmXo...',
    documentName: 'कागजात नाम',
    documentNamePlaceholder: 'कागजात नाम प्रविष्ट गर्नुहोस्',

    // Close
    closeTitle: 'परियोजना बन्द (अन-चेन)',
    closeWarning: '⚠️ चेतावनी: परियोजना बन्द गर्नु स्थायी हो र अन-चेनमा रेकर्ड हुन्छ। त्यसपछि कुनै परिवर्तन हुन सक्दैन।',
    selectActiveProject: 'सक्रिय परियोजना छान्नुहोस्',

    // Messages
    programNotLoaded: 'प्रोग्राम लोड भएन। पहिले वालेट जडान गर्नुहोस्।',
    connectFirst: 'पहिले वालेट जडान गर्नुहोस्।',
    projectCreated: 'परियोजना अन-चेनमा सिर्जना भयो!',
    budgetAllocated: 'बजेट अन-चेनमा विनियोजित भयो!',
    fundsReleased: 'कोष अन-चेनमा विमोचित भयो!',
    milestoneUpdated: 'माइलस्टोन अन-चेनमा अपडेट भयो!',
    documentRecorded: 'कागजात अन-चेनमा रेकर्ड भयो!',
    projectClosed: 'परियोजना अन-चेनमा बन्द भयो!',
    txLabel: 'TX',
    fillAllFields: 'कृपया सबै आवश्यक फिल्डहरू भर्नुहोस्।',
    invalidProgramId: 'अमान्य Program ID। कृपया .env कन्फिगरेसन जाँच गर्नुहोस्।',

    // Navbar
    home: 'गृहपृष्ठ',
    dashboard: 'ड्यासबोर्ड',
    projects: 'परियोजनाहरू',

    // Dashboard
    dashboardTitle: 'परियोजना अवलोकन',
    dashboardSubtitle: 'सबै सरकारी परियोजनाहरूको वास्तविक-समय विश्लेषण र स्वास्थ्य',
    totalBudgetLabel: 'कुल बजेट',
    allocated: 'विनियोजित',
    released: 'विमोचित',
    projectsLabel: 'परियोजनाहरू',
    active: 'सक्रिय',
    utilization: 'उपयोग',
    provinceSpending: 'प्रदेश-अनुसार खर्च',
    sectorDistribution: 'क्षेत्र वितरण',
    overallBudgetUtilization: 'समग्र बजेट उपयोग',
    allocatedTotalBudget: 'विनियोजित / कुल बजेट',
    releasedAllocated: 'विमोचित / विनियोजित',
    allocatedSuffix: 'विनियोजित',
    totalSuffix: 'कुल',
    releasedSuffix: 'विमोचित',
    unallocatedFunds: 'अविनियोजित कोष',
    exploreAllProjects: 'सबै परियोजनाहरू हेर्नुहोस् →',
    totalProjectsLabel: 'कुल परियोजनाहरू',
    activeProjectsOverview: 'सक्रिय परियोजनाहरू',
    delayedProjectsLabel: 'ढिला परियोजनाहरू',
    completedProjectsLabel: 'सम्पन्न परियोजनाहरू',
    projectsByProvince: 'प्रदेश-अनुसार परियोजनाहरू',
    projectStatusBreakdown: 'परियोजना स्थिति विश्लेषण',
    projectsBySector: 'क्षेत्र-अनुसार परियोजनाहरू',
    milestoneProgressByProject: 'परियोजना-अनुसार माइलस्टोन प्रगति',
    recentFundReleases: 'हालैका कोष विमोचनहरू',
    recentlyUpdated: 'हालसालै अपडेट भएका',
    totalLabel: 'कुल',
    completedLabel: 'पूरा',
    progressLabel: 'प्रगति',
    viewProjectLink: 'हेर्नुहोस् →',
    noRecentReleases: 'हालैका कोष विमोचन छैन',

    // Projects page
    closed: 'बन्द',
    contractorLabel: 'ठेकेदार',
    fundUtilization: 'कोष उपयोग',
    milestonesLabel: 'माइलस्टोनहरू',
    estCompletion: 'अनुमानित समापन',
    govProjects: 'सरकारी परियोजनाहरू',
    browseProjects: 'नेपालभरका सबै वित्तपोषित परियोजनाहरू ब्राउज र प्रमाणित गर्नुहोस्',
    allProvinces: 'सबै प्रदेशहरू',
    allSectors: 'सबै क्षेत्रहरू',
    allStatus: 'सबै स्थिति',
    activeStatus: 'सक्रिय',
    completedStatus: 'सम्पन्न',
    suspendedStatus: 'स्थगित',
    showing: 'देखाउँदै',
    of: 'मध्ये',
    noProjectsMatch: 'तपाईंको फिल्टरसँग कुनै परियोजना मेल खाएन',

    // ProjectDetail
    projectNotFound: 'परियोजना फेला परेन',
    demonstrationProject: 'प्रदर्शन परियोजना',
    demoProjectDesc: 'यो परियोजनाले प्रदर्शन उद्देश्यका लागि नमूना डाटा प्रयोग गर्छ। यहाँ देखाइएका लेनदेन रेकर्डहरू सिमुलेटेड छन्। प्रत्यक्ष अन-चेन लेनदेनहरू व्यवस्थापक कार्यहरू मार्फत सोलाना devnet मा दर्ता भएपछि देखा पर्नेछन्।',
    completion: 'समापन',
    milestonePipeline: 'माइलस्टोन पाइपलाइन',
    noMilestones: 'अहिलेसम्म कुनै माइलस्टोन रेकर्ड गरिएको छैन',
    fundReleaseTimeline: 'कोष विमोचन समयरेखा',
    fundReleaseHistory: 'कोष विमोचन इतिहास',
    dateLabel: 'मिति',
    amountLabel: 'रकम',
    descriptionLabel: 'विवरण',
    publicReviews: 'सार्वजनिक समीक्षा',
    ratingLabel: 'मूल्यांकन:',
    feedbackPlaceholder: 'यो परियोजनाबारे आफ्नो प्रतिक्रिया साझा गर्नुहोस्...',
    submittingFeedback: 'पेश गर्दै...',
    submitReview: 'समीक्षा पेश गर्नुहोस्',
    noReviews: 'अहिलेसम्म समीक्षा छैन। पहिलो हुनुहोस्!',
    documentsIPFS: 'कागजातहरू (IPFS)',
    noDocuments: 'अहिलेसम्म कुनै कागजात अपलोड गरिएको छैन',
    budgetAllocationsTitle: 'बजेट विनियोजनहरू',
    onChainData: 'अन-चेन डाटा',
    projectPDA: 'परियोजना PDA (Devnet)',
    recentTransactions: 'हालैका लेनदेनहरू',
    transactionHistory: 'लेनदेन इतिहास',
    sampleData: 'नमूना डाटा',
    sampleTxNote: 'यो परियोजनाले प्रदर्शनको लागि नमूना लेनदेन डाटा प्रयोग गर्छ। सोलाना devnet मा व्यवस्थापक कार्यहरू मार्फत रेकर्ड भएपछि प्रत्यक्ष अन-चेन लेनदेनहरू यहाँ देखा पर्नेछन्।',
    noOnChainTx: 'अहिलेसम्म अन-चेन लेनदेन रेकर्ड छैन।',
    solanaExplorer: 'सोलाना एक्सप्लोरर',
    devnetCluster: 'Devnet क्लस्टर',
    estimatedCompletionLabel: 'अनुमानित समापन',

    // Landing
    builtOnSolana: 'सोलाना ब्लकचेनमा निर्मित',
    transparentTitle: 'पारदर्शी',
    governmentFunds: 'सरकारी कोष',
    forNepal: 'नेपालको लागि',
    heroSubtitle: 'प्रत्येक रुपैयाँ ट्र्याक गरिन्छ। प्रत्येक परियोजना प्रमाणित हुन्छ। भ्रष्टाचार',
    technicallyRestricted: ' प्राविधिक रूपमा प्रतिबन्धित ',
    heroSubtitleEnd: 'ब्लकचेन नियमहरूद्वारा — खाली वाचाहरूले होइन।',
    viewBudget: 'बजेट हेर्नुहोस् →',
    exploreProjectsBtn: 'परियोजनाहरू हेर्नुहोस्',
    immutableRecords: 'अपरिवर्तनीय रेकर्डहरू',
    publicVerification: 'सार्वजनिक प्रमाणीकरण',
    noTampering: 'छेडछाड नहुने',
    transparencyGlance: 'पारदर्शिता एक नजरमा',
    realtimeBlockchainData: 'सोलाना ब्लकचेनबाट वास्तविक-समय डाटा',
    fundsReleasedLabel: 'कोष विमोचित',
    activeProjectsLabel: 'सक्रिय परियोजनाहरू',
    utilizationRateLabel: 'उपयोग दर',
    howItWorks: 'यसले कसरी काम गर्छ',
    blockchainSteps: 'ब्लकचेन-लागू पारदर्शिता ४ चरणमा',
    stepProjectCreated: 'परियोजना सिर्जना',
    stepProjectCreatedDesc: 'सरकारले पूर्ण बजेट विवरणसहित ब्लकचेनमा सार्वजनिक परियोजना सिर्जना गर्छ।',
    stepBudgetAllocated: 'बजेट विनियोजित',
    stepBudgetAllocatedDesc: 'कोषबाट रकम विनियोजन गरिन्छ। घोषित कुल बजेट भन्दा बढी हुन सक्दैन — स्मार्ट कन्ट्र्याक्टद्वारा लागू।',
    stepFundsReleased: 'कोष विमोचित',
    stepFundsReleasedDesc: 'प्रत्येक विमोचन अन-चेनमा रेकर्ड गरिन्छ। विनियोजित रकम भन्दा बढी हुन सक्दैन। छेडछाड-प्रमाण इतिहास।',
    stepPublicVerification: 'सार्वजनिक प्रमाणीकरण',
    stepPublicVerificationDesc: 'कुनै पनि नागरिकले सोलाना एक्सप्लोररमा लेनदेन प्रमाणित गर्न सक्छन्। पूर्ण पारदर्शिता, शून्य विश्वास आवश्यक।',
    whyBlockchain: 'किन ब्लकचेन?',
    corruptionTitle: 'भ्रष्टाचार अन-चेनमा बाँच्न सक्दैन',
    corruptionDesc: 'परम्परागत सरकारी बजेट ट्र्याकिङ केन्द्रीकृत डेटाबेसमा निर्भर हुन्छ जुन हेरफेर गर्न सकिन्छ। हाम्रो प्रणालीले प्रत्येक वित्तीय लेनदेन सोलाना ब्लकचेनमा भण्डारण गर्छ — अपरिवर्तनीय, पारदर्शी, र कुनै पनि नागरिकद्वारा प्रमाणित।',
    immutableLedger: 'अपरिवर्तनीय लेजर',
    immutableLedgerDesc: 'एक पटक रेकर्ड गरिसकेपछि, लेनदेनहरू परिवर्तन वा मेटाउन सकिँदैन',
    smartContractRules: 'स्मार्ट कन्ट्र्याक्ट नियमहरू',
    smartContractRulesDesc: 'बजेट सीमाहरू कोडद्वारा लागू, प्रशासकहरूद्वारा होइन',
    realtimeAuditing: 'वास्तविक-समय लेखापरीक्षा',
    realtimeAuditingDesc: 'जो कोहीले सोलाना एक्सप्लोरर मार्फत प्रमाणित गर्न सक्छन् — FOIA आवश्यक छैन',
    readyToExplore: 'हेर्न तयार हुनुहुन्छ',
    transparentGovernance: 'पारदर्शी शासन?',
    connectWalletCTA: 'आफ्नो सोलाना वालेट जडान गर्नुहोस् र वास्तविक-समयमा सरकारी खर्च प्रमाणित गर्न सुरु गर्नुहोस्। प्रत्येक लेनदेन अन-चेन र सार्वजनिक रूपमा लेखापरीक्षायोग्य छ।',

    // Welcome
    welcomeTagline1: 'पारदर्शी शासन,',
    welcomeTagline2: 'अन-चेन।',
    welcomeTagline3: 'सबैका लागि।',
    welcomeSubtitle: 'सरकारी खर्चको प्रत्येक रुपैयाँ ट्र्याक गर्ने विकेन्द्रीकृत DApp — अपरिवर्तनीय, प्रमाणित, र प्रत्येक नेपाली नागरिकका लागि खुला।',
    letsExplore: 'अन्वेषण गरौं',
    solanaBlockchainBadge: 'सोलाना ब्लकचेन',
    immutableRecordsBadge: 'अपरिवर्तनीय रेकर्डहरू',
    builtForNepal: 'नेपालको लागि निर्मित',
    decentralizedStrip: 'विकेन्द्रीकृत · पारदर्शी · विश्वासरहित',

    // Footer
    footerDesc: 'सोलाना ब्लकचेनमा निर्मित विकेन्द्रीकृत सरकारी कोष पारदर्शिता प्रणाली। नेपालका प्रत्येक नागरिकका लागि सार्वजनिक खर्च पारदर्शी, अपरिवर्तनीय, र प्रमाणित बनाउँदै।',
    quickLinks: 'छिटो लिंकहरू',
    adminPanel: 'प्रशासक प्यानल',
    blockchainLabel: 'ब्लकचेन',
    devnetConnected: 'Devnet जडित',
    copyright: '© २०२६ GovFund Nepal। सोलाना ब्लकचेनमा निर्मित। सबै लेनदेनहरू सार्वजनिक रूपमा प्रमाणित छन्।',
    forTransparentNepal: 'पारदर्शी नेपालको लागि',

    // ErrorBoundary
    somethingWrong: 'केही गलत भयो',
    unexpectedError: 'अप्रत्याशित त्रुटि भयो। यो अस्थायी समस्या हुन सक्छ।',
    showErrorDetails: 'त्रुटि विवरण देखाउनुहोस्',
    tryAgain: 'पुन: प्रयास गर्नुहोस्',
    reloadPage: 'पृष्ठ पुन: लोड गर्नुहोस्',
    errorHelp: 'यो समस्या दोहोरिँदो भए, आफ्नो वालेट जडान जाँच गर्नुहोस् र सोलाना प्रोग्राम Devnet मा तैनात भएको सुनिश्चित गर्नुहोस्।',

    // IPFS
    connectingIPFS: 'IPFS मा जडान हुँदैछ…',
    connectingGateway: 'IPFS गेटवेमा जडान हुँदैछ…',
    checkingGateways: 'बहु गेटवेहरू जाँच गर्दै',
    gatewayUnavailable: 'गेटवे उपलब्ध छैन',
    tryDirectly: 'सिधै खोल्ने प्रयास गर्नुहोस् →',
    ipfsDocumentLabel: 'IPFS कागजात',

    // National Budget
    budgetTitle: 'राष्ट्रिय बजेट पारदर्शिता',
    budgetSubtitle: 'अन-चेन प्रमाणिकरणसहित पूर्ण आर्थिक विश्लेषण',
    budgetNoData: 'बजेट डाटा उपलब्ध छैन',
    budgetTotalAllocated: 'कुल विनियोजित बजेट',
    budgetTotalSpent: 'अहिलेसम्म खर्च भएको',
    budgetOverallUtil: 'समग्र उपयोग दर',
    budgetSplitTitle: 'बजेट विभाजन',
    budgetRecurrent: 'चालू खर्च',
    budgetCapital: 'पूँजीगत खर्च',
    budgetFinancialMgmt: 'वित्तीय व्यवस्थापन',
    budgetProvinceGrants: 'प्रदेश-अनुसार संघीय अनुदान',
    budgetFederalGrant: 'संघीय अनुदान (अर्ब रु.)',
    budgetMinistryBreakdown: 'मन्त्रालय-अनुसार बजेट विभाजन',
    budgetAmount: 'बजेट (अर्ब रु.)',
    budgetUtilization: 'बजेट उपयोग',
    budgetAllocatedLabel: 'विनियोजित',
    budgetSpentLabel: 'खर्च भएको',
    budgetCriticallyLow: 'अत्यन्त न्यून',
    budgetCat_Total: 'कुल',
    budgetCat_Recurrent: 'चालू',
    budgetCat_Capital: 'पूँजीगत',
    budgetCat_FinancialManagement: 'वित्तीय व्यवस्थापन',
    budgetIpfsTitle: 'छेडछाड-प्रमाण IPFS प्रमाणिकरण',
    budgetIpfsPending: 'बजेट डाटा अझै IPFS मा अपलोड गरिएको छैन',
    budgetVerifyIpfs: 'IPFS मा प्रमाणित गर्नुहोस्',
    budget: 'बजेट',
  },
};

const LanguageContext = createContext({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
});

export { LanguageContext };

export function useLanguage() {
  return useContext(LanguageContext);
}

export default function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      return localStorage.getItem('govfund-lang') || 'en';
    } catch {
      return 'en';
    }
  });

  const setLang = useCallback((newLang) => {
    setLangState(newLang);
    try {
      localStorage.setItem('govfund-lang', newLang);
    } catch {}
  }, []);

  const t = useCallback(
    (key) => {
      return translations[lang]?.[key] || translations.en?.[key] || key;
    },
    [lang]
  );

  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}
